language: android
sudo: false
jdk: oraclejdk8
before_script:
  - service postgresql stop || true
  - service mysql stop || true
  - service bootlogd stop || true
  - service elasticsearch stop || true
  - service mongodb stop || true
  - service neo4j stop || true
  - service cassandra stop || true
  - service memcached stop || true
  - service riak stop || true
  - service rsync stop || true
  - service x11-common stop || true
android:
  components:
  - tools
  - build-tools-23.0.2
  - android-23
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
notifications:
  email: false
  slack:
    rooms:
      secure: NVkh+VYIPnEfR7oPbjuWlh+bSJvOUUL6WjKdY5MZ5ejyYjuF8/e2NBSSvdOv+uA7/ah4BP8IHhrppZi14O9X0WzhtVaraKX9WXmTrBmyqNZsCtxx/xtEi+Fho8ZWy7c1YxbdiLD9m7IvDQ+CFs8OyDbQTK2SH2b4Ut5FjY9jELZJRnuJ6KrPLdmw4fRcyiT6WdbySZCyt1TUWSgMPzFYDD+JDhr7VHtu4rb5+gl9hgk3Uory1r2blxzAybrrd8fTtbM3+W94FRhdIhhuJ1AQ9fApQrW2cJqmEnwoOOOMKlfmXKMRC92HxoFStLSiOCkAMxlNIAZmoHtvl+b1kA4U+oQ6pK/BrTKlrUA4cMTsAuoxPJba5Sn6QRi+wJpwxwUr6AuDDkdvxuqFD0LP0RdJGN0KaNoSo6naBNAsKbwgdzwr64T3FjShp38Z2zqObp79iDaE9liIkQcsSUHs8c7qCUfMd0NQOk5mq5q4j/3SkBBf1Vlbe0l7VsULdgPxl6wVXlnL53popdrDZHGKv2k7y46o5JmPjxxIqHGTT3+M6GmGqBgTQf5tj9754uJeMkACaZnYBaefOBdGyUng7al5o6Xjuril2xxmHm8yjwzauztc81HDG71YQwudAU3cK6JhHAYDs8sMqPDsKhQKj0h+ZsRyBgHB++c3ci2V3edMit4=
